### ISSUE TITLE
Jupyter notebook doesn't start and returns errors: KeyError: 'cookie_secret' and TypeError: Missing required parameter 'digestmod'.

### ISSUE THREAD

**Issue by gekaklam** [the-full-stack/fsdl-text-recognizer-2022#65]
Hi,

I've just cloned this repo on a new anaconda installation, Ubuntu 20.04. I followed the instructions and after the "make pip-tools" finished, I tried to run "jupyter notebook".  I'm getting the following error. 

I've spent quite some time trying to troubleshoot this with no success. **Can someone confirm if they're having the same issues or if it's just me?**

```bash
(fsdl-text-recognizer-2022) gekaklam@eru:~/projects/fsdl-text-recognizer-2022$ jupyter notebook
Traceback (most recent call last):
  File "/home/gekaklam/anaconda3/envs/fsdl-text-recognizer-2022/lib/python3.8/site-packages/traitlets/traitlets.py", line 537, in get
    value = obj._trait_values[self.name]
KeyError: 'cookie_secret'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gekaklam/anaconda3/envs/fsdl-text-recognizer-2022/bin/jupyter-notebook", line 8, in <module>
    sys.exit(main())
  File "/home/gekaklam/anaconda3/envs/fsdl-text-recognizer-2022/lib/python3.8/site-packages/jupyter_core/application.py", line 264, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/home/gekaklam/anaconda3/envs/fsdl-text-recognizer-2022/lib/python3.8/site-packages/traitlets/config/application.py", line 845, in launch_instance
    app.initialize(argv)
  File "/home/gekaklam/anaconda3/envs/fsdl-text-recognizer-2022/lib/python3.8/site-packages/traitlets/config/application.py", line 88, in inner
    return method(app, *args, **kwargs)
  File "/home/gekaklam/anaconda3/envs/fsdl-text-recognizer-2022/lib/python3.8/site-packages/notebook/notebookapp.py", line 1507, in initialize
    self.init_webapp()
  File "/home/gekaklam/anaconda3/envs/fsdl-text-recognizer-2022/lib/python3.8/site-packages/notebook/notebookapp.py", line 1265, in init_webapp
    self.web_app = NotebookWebApplication(
  File "/home/gekaklam/anaconda3/envs/fsdl-text-recognizer-2022/lib/python3.8/site-packages/notebook/notebookapp.py", line 152, in __init__
    settings = self.init_settings(
  File "/home/gekaklam/anaconda3/envs/fsdl-text-recognizer-2022/lib/python3.8/site-packages/notebook/notebookapp.py", line 247, in init_settings
    cookie_secret=jupyter_app.cookie_secret,
  File "/home/gekaklam/anaconda3/envs/fsdl-text-recognizer-2022/lib/python3.8/site-packages/traitlets/traitlets.py", line 577, in __get__
    return self.get(obj, cls)
  File "/home/gekaklam/anaconda3/envs/fsdl-text-recognizer-2022/lib/python3.8/site-packages/traitlets/traitlets.py", line 540, in get
    default = obj.trait_defaults(self.name)
  File "/home/gekaklam/anaconda3/envs/fsdl-text-recognizer-2022/lib/python3.8/site-packages/traitlets/traitlets.py", line 1580, in trait_defaults
    return self._get_trait_default_generator(names[0])(self)
  File "/home/gekaklam/anaconda3/envs/fsdl-text-recognizer-2022/lib/python3.8/site-packages/traitlets/traitlets.py", line 977, in __call__
    return self.func(*args, **kwargs)
  File "/home/gekaklam/anaconda3/envs/fsdl-text-recognizer-2022/lib/python3.8/site-packages/notebook/notebookapp.py", line 709, in _default_cookie_secret
    h = hmac.HMAC(key)
  File "/home/gekaklam/anaconda3/envs/fsdl-text-recognizer-2022/lib/python3.8/hmac.py", line 51, in __init__
    raise TypeError("Missing required parameter 'digestmod'.")
TypeError: Missing required parameter 'digestmod'.
```

**Comment by rrrventures** [comment]
I'm pretty stuck on this too. Did you manage to fix this?

**Comment by charlesfrye** [comment]
should be fixed now! required a version bump of the `notebook` library
